### ISSUE TITLE
as.scalar() error?

### ISSUE THREAD

**Issue by calebasaraba** [ecohealthalliance/metaflu#17]
Not sure what is happening here -- fig2 function sets up parameters and network based on figure 2 in published paper and arguments for number of farms and number of animals per farm. 

This error has occurred in two runs of this particular configuration (farm size = 40, number of farms = 800). 

![image](https://cloud.githubusercontent.com/assets/21368926/20155440/e86359fa-a699-11e6-9f58-0b81b978c7f7.png)

**Comment by noamross** [comment]
Fixed under the new high speed implementation.
