### ISSUE TITLE
Keep track of infections

### ISSUE THREAD

**Issue by calebasaraba** [ecohealthalliance/metaflu#18]
Add code to track cumulative number of infections, SIRV matrix does not provide this information -- CNB not sure how best to add this into C functions.

**Comment by noamross** [comment]
So, tally the number of new infection events?

**Comment by calebasaraba** [comment]
Yep, wasn't sure how to best store / pass a variable like that around in there.

**Comment by noamross** [comment]
Can you calculate the approx number of infections between time points based on the current output, so we can see how well it matches up with the exact count?  It should basically be the change in I corrected for the number of recoveries (increase in R) and deaths (a constant fraction).

**Comment by calebasaraba** [comment]
Got it.
