### ISSUE TITLE
Record Initial Conditions

### ISSUE THREAD

**Issue by calebasaraba** [ecohealthalliance/metaflu#19]
Record initial SIRV conditions as first time point.

Actually, after review, this may just be a numbering issue -- entering times 0:2000 gives an output with times 1:2001.

**Comment by noamross** [comment]
Oh, will check that out.  The switch between 0- and 1-based indexing in R and C always trips me up.

**Comment by noamross** [comment]
Is this fixed in he current iteration?

**Comment by calebasaraba** [comment]
Yes -- just double-checked: closed.
