### ISSUE TITLE
Tests for parallelism and reproducibility on simulator

### ISSUE THREAD

**Issue by noamross** [ecohealthalliance/metaflu#4]
-  Setting seed should result in same results parallel or not
-  Setting seed should NOT result in same results across patches or simulations
-  Also test against a model saved as RDS with same seed
-  non-seeded run after seeded run should not always be the same

See http://r-pkgs.had.co.nz/tests.html

**Comment by calebasaraba** [comment]
Did you already fix?

-non-seeded run after seeded run should not always be the same

Test keeps passing now...

**Comment by noamross** [comment]
Yes!  #9 fixed this
